# Generated by Django 6.0.3 on 2026-06-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_proof',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
