# Generated by Django 6.0.3 on 2026-07-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_currentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(default='Customer', max_length=100),
        ),
    ]
