# Generated by Django 6.0.3 on 2026-07-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='edit_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
